---
title: Bitrise DevCenter
email: letsconnect@bitrise.io
description: Bitrise is a Continuous Integration and Delivery (CI/CD) Platform as
  a Service (PaaS) with a main focus on mobile app development. It saves developers
  hours every day by automating tasks that are boring and repetitive from the moment
  they finish coding till the app lands in an app store.
baseurl: ''
url: ''
twitter_username: jekyllrb
github_username: jekyll
markdown: kramdown
theme: minima
plugins:
- jekyll-feed
- jekyll-sitemap
- jekyll-menus
- jekyll-redirect-from
collections:
  articles:
    output: true
    permalink: "/:path/"
defaults:
- scope:
    path: ''
    type: articles
  values:
    layout: default
sass:
  load_paths:
  - _sass
  - node_modules
timezone: Etc/UTC
